---
baseURL: "/security/"
languageCode: "en-us"
title: "Product Security Guide"
theme: "camunda"

blackfriday:
  plainIDAnchors: true

params:
  sections:
    - id: "get-started"
      name: "Get Started"
      url: "/get-started"
    - id: "manual"
      name: "Camunda Platform"
      url: "/manual"
    - id: "optimize"
      name: "Optimize"
      url: "/optimize"
    - id: 'cawemo'
      name: 'Cawemo'
      url: '/cawemo'
    - id: "enterprise"
      name: "Enterprise"
      url: "/enterprise"
    - id: "security"
      name: "Security"
      url: "/security"
  section:
    id: "security"
  github:
    repositoryName: "camunda/camunda-docs-static"
    branch: "master/security"

outputs:
  home:
    - "HTML"
    - "RSS"
  section:
    - "HTML"

disableKinds:
- taxonomy
- taxonomyTerm
...
